export const MOC_Products = {
  "pages": 5,
  "current_page": 1,
  "limit": 10,
  "products": [
      {
          "id": 1,
          "name": "Смартфон X100",
          "description": "Флагманский смартфон с OLED-дисплеем",
          "price": 199.99,
          "discount_price": 199.99,
          "stock": 10,
          "category": "Электроника",
          "created_at": "2023-06-10",
          "updated_at": "2024-02-01",
          "brand": "Apple",
          "weight": 0.5,
          "dimensions": "10x5x2",
          "color": "Черный",
          "rating": 4.5,
          "reviews_count": 100,
          "images": ["/media/img1.jpg", "/media/img2.jpg"],
          "seller_id": 101,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "1234567890123"
      },
      {
          "id": 2,
          "name": "Ноутбук ProBook 15",
          "description": "Мощный ноутбук для работы и игр",
          "price": 899.99,
          "discount_price": 849.99,
          "stock": 5,
          "category": "Электроника",
          "created_at": "2023-05-15",
          "updated_at": "2024-01-20",
          "brand": "HP",
          "weight": 2.0,
          "dimensions": "15x10x1",
          "color": "Серебристый",
          "rating": 4.7,
          "reviews_count": 150,
          "images": ["/media/img3.jpg", "/media/img4.jpg"],
          "seller_id": 102,
          "warranty_period": 24,
          "return_policy": "30 дней на возврат",
          "barcode": "2345678901234"
      },
      {
          "id": 3,
          "name": "Наушники SoundMax",
          "description": "Беспроводные наушники с шумоподавлением",
          "price": 149.99,
          "discount_price": 129.99,
          "stock": 20,
          "category": "Аксессуары",
          "created_at": "2023-07-01",
          "updated_at": "2024-01-25",
          "brand": "Sony",
          "weight": 0.3,
          "dimensions": "8x6x3",
          "color": "Белый",
          "rating": 4.8,
          "reviews_count": 200,
          "images": ["/media/img5.jpg", "/media/img6.jpg"],
          "seller_id": 103,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "3456789012345"
      },
      {
          "id": 4,
          "name": "Фитнес-браслет FitBand 5",
          "description": "Умный браслет с мониторингом здоровья",
          "price": 79.99,
          "discount_price": 69.99,
          "stock": 30,
          "category": "Гаджеты",
          "created_at": "2023-08-12",
          "updated_at": "2024-01-30",
          "brand": "Xiaomi",
          "weight": 0.1,
          "dimensions": "6x2x1",
          "color": "Черный",
          "rating": 4.6,
          "reviews_count": 180,
          "images": ["/media/img7.jpg", "/media/img8.jpg"],
          "seller_id": 104,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "4567890123456"
      },
      {
          "id": 5,
          "name": "Электронная книга Reader Pro",
          "description": "Электронная книга с E-Ink дисплеем",
          "price": 129.99,
          "discount_price": 119.99,
          "stock": 15,
          "category": "Электроника",
          "created_at": "2023-09-05",
          "updated_at": "2024-02-05",
          "brand": "Amazon",
          "weight": 0.4,
          "dimensions": "12x8x1",
          "color": "Серый",
          "rating": 4.4,
          "reviews_count": 90,
          "images": ["/media/img9.jpg", "/media/img10.jpg"],
          "seller_id": 105,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "5678901234567"
      },
      {
          "id": 6,
          "name": "Умные часы Watch 3",
          "description": "Умные часы с функцией мониторинга сна",
          "price": 199.99,
          "discount_price": 179.99,
          "stock": 25,
          "category": "Гаджеты",
          "created_at": "2023-10-10",
          "updated_at": "2024-02-10",
          "brand": "Samsung",
          "weight": 0.2,
          "dimensions": "4x4x1",
          "color": "Синий",
          "rating": 4.9,
          "reviews_count": 250,
          "images": ["/media/img11.jpg", "/media/img12.jpg"],
          "seller_id": 106,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "6789012345678"
      },
      {
          "id": 7,
          "name": "Планшет Tab 10",
          "description": "Планшет с экраном 10 дюймов",
          "price": 299.99,
          "discount_price": 279.99,
          "stock": 8,
          "category": "Электроника",
          "created_at": "2023-11-15",
          "updated_at": "2024-02-15",
          "brand": "Lenovo",
          "weight": 0.6,
          "dimensions": "10x7x0.5",
          "color": "Серебристый",
          "rating": 4.3,
          "reviews_count": 120,
          "images": ["/media/img13.jpg", "/media/img14.jpg"],
          "seller_id": 107,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "7890123456789"
      },
      {
          "id": 8,
          "name": "Камера ActionCam 4K",
          "description": "Экшн-камера с поддержкой 4K",
          "price": 249.99,
          "discount_price": 229.99,
          "stock": 12,
          "category": "Фото и видео",
          "created_at": "2023-12-01",
          "updated_at": "2024-02-20",
          "brand": "GoPro",
          "weight": 0.3,
          "dimensions": "6x4x2",
          "color": "Черный",
          "rating": 4.7,
          "reviews_count": 170,
          "images": ["/media/img15.jpg", "/media/img16.jpg"],
          "seller_id": 108,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "8901234567890"
      },
      {
          "id": 9,
          "name": "Игровая консоль GameBox X",
          "description": "Игровая консоль нового поколения",
          "price": 499.99,
          "discount_price": 479.99,
          "stock": 3,
          "category": "Игры",
          "created_at": "2024-01-01",
          "updated_at": "2024-02-25",
          "brand": "Microsoft",
          "weight": 3.5,
          "dimensions": "30x20x10",
          "color": "Черный",
          "rating": 4.8,
          "reviews_count": 300,
          "images": ["/media/img17.jpg", "/media/img18.jpg"],
          "seller_id": 109,
          "warranty_period": 24,
          "return_policy": "30 дней на возврат",
          "barcode": "9012345678901"
      },
      {
          "id": 10,
          "name": "Монитор UltraView 27",
          "description": "27-дюймовый монитор с разрешением 4K",
          "price": 399.99,
          "discount_price": 379.99,
          "stock": 7,
          "category": "Электроника",
          "created_at": "2024-01-10",
          "updated_at": "2024-02-28",
          "brand": "Dell",
          "weight": 5.0,
          "dimensions": "27x20x2",
          "color": "Черный",
          "rating": 4.6,
          "reviews_count": 140,
          "images": ["/media/img19.jpg", "/media/img20.jpg"],
          "seller_id": 110,
          "warranty_period": 24,
          "return_policy": "30 дней на возврат",
          "barcode": "0123456789012"
      },
      {
          "id": 11,
          "name": "Портативная колонка JBL",
          "description": "Bluetooth колонка с высоким качеством звука",
          "price": 99.99,
          "discount_price": 89.99,
          "stock": 25,
          "category": "Аудио",
          "created_at": "2024-01-15",
          "updated_at": "2024-02-15",
          "brand": "JBL",
          "weight": 0.8,
          "dimensions": "8x3x3",
          "color": "Синий",
          "rating": 4.5,
          "reviews_count": 110,
          "images": ["/media/img21.jpg", "/media/img22.jpg"],
          "seller_id": 111,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "abc123456789"
      },
      {
          "id": 12,
          "name": "Кофейная машина Espresso",
          "description": "Кофейная машина с функцией капучино",
          "price": 349.99,
          "discount_price": 329.99,
          "stock": 20,
          "category": "Кухня",
          "created_at": "2024-01-20",
          "updated_at": "2024-02-20",
          "brand": "Nespresso",
          "weight": 2.5,
          "dimensions": "12x12x12",
          "color": "Серый",
          "rating": 4.0,
          "reviews_count": 75,
          "images": ["/media/img23.jpg", "/media/img24.jpg"],
          "seller_id": 112,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "def123456789"
      },
      {
          "id": 13,
          "name": "Вакуумный упаковщик",
          "description": "Упаковщик для хранения продуктов",
          "price": 79.99,
          "discount_price": 69.99,
          "stock": 50,
          "category": "Кухня",
          "created_at": "2024-01-25",
          "updated_at": "2024-02-25",
          "brand": "FoodSaver",
          "weight": 1.2,
          "dimensions": "15x10x5",
          "color": "Черный",
          "rating": 4.2,
          "reviews_count": 65,
          "images": ["/media/img25.jpg", "/media/img26.jpg"],
          "seller_id": 113,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "ghi123456789"
      },
      {
          "id": 14,
          "name": "Фен DeLonghi",
          "description": "Фен с функцией ионизации",
          "price": 59.99,
          "discount_price": 49.99,
          "stock": 30,
          "category": "Красота",
          "created_at": "2024-02-01",
          "updated_at": "2024-03-01",
          "brand": "DeLonghi",
          "weight": 0.7,
          "dimensions": "8x3x3",
          "color": "Розовый",
          "rating": 4.5,
          "reviews_count": 40,
          "images": ["/media/img27.jpg", "/media/img28.jpg"],
          "seller_id": 114,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "jkl123456789"
      },
      {
          "id": 15,
          "name": "Косметический набор",
          "description": "Набор косметики для ухода за кожей",
          "price": 99.99,
          "discount_price": 89.99,
          "stock": 40,
          "category": "Красота",
          "created_at": "2024-02-05",
          "updated_at": "2024-03-05",
          "brand": "L'Oreal",
          "weight": 0.5,
          "dimensions": "10x10x5",
          "color": "Многоцветный",
          "rating": 4.6,
          "reviews_count": 55,
          "images": ["/media/img29.jpg", "/media/img30.jpg"],
          "seller_id": 115,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "mno123456789"
      },
      {
          "id": 16,
          "name": "Чистящие средства для кухни",
          "description": "Набор чистящих средств для кухни",
          "price": 39.99,
          "discount_price": 34.99,
          "stock": 60,
          "category": "Уборка",
          "created_at": "2024-02-10",
          "updated_at": "2024-03-10",
          "brand": "Mr. Clean",
          "weight": 1.0,
          "dimensions": "15x10x5",
          "color": "Синий",
          "rating": 4.2,
          "reviews_count": 28,
          "images": ["/media/img31.jpg", "/media/img32.jpg"],
          "seller_id": 116,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "pqr123456789"
      },
      {
          "id": 17,
          "name": "Смартфон Galaxy S21",
          "description": "Смартфон с 5G и быстрой зарядкой",
          "price": 999.99,
          "discount_price": 949.99,
          "stock": 15,
          "category": "Электроника",
          "created_at": "2024-02-15",
          "updated_at": "2024-03-15",
          "brand": "Samsung",
          "weight": 0.4,
          "dimensions": "6.2x2.8x0.3",
          "color": "Черный",
          "rating": 4.9,
          "reviews_count": 300,
          "images": ["/media/img33.jpg", "/media/img34.jpg"],
          "seller_id": 117,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "stu123456789"
      },
      {
          "id": 18,
          "name": "Электрический чайник",
          "description": "Чайник с автоотключением и подсветкой",
          "price": 49.99,
          "discount_price": 39.99,
          "stock": 100,
          "category": "Кухня",
          "created_at": "2024-02-20",
          "updated_at": "2024-03-20",
          "brand": "Bosch",
          "weight": 1.0,
          "dimensions": "8x8x10",
          "color": "Серебристый",
          "rating": 4.4,
          "reviews_count": 45,
          "images": ["/media/img35.jpg", "/media/img36.jpg"],
          "seller_id": 118,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "vwx123456789"
      },
      {
          "id": 19,
          "name": "Робот-пылесос",
          "description": "Умный пылесос с функцией планирования",
          "price": 299.99,
          "discount_price": 279.99,
          "stock": 20,
          "category": "Уборка",
          "created_at": "2024-02-25",
          "updated_at": "2024-03-25",
          "brand": "Xiaomi",
          "weight": 3.0,
          "dimensions": "12x12x3",
          "color": "Белый",
          "rating": 4.8,
          "reviews_count": 150,
          "images": ["/media/img37.jpg", "/media/img38.jpg"],
          "seller_id": 119,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "yz1234567890"
      },
      {
          "id": 20,
          "name": "Игра для PS5",
          "description": "Новая игра для PlayStation 5",
          "price": 59.99,
          "discount_price": 49.99,
          "stock": 40,
          "category": "Игры",
          "created_at": "2024-03-01",
          "updated_at": "2024-03-10",
          "brand": "Sony",
          "weight": 0.2,
          "dimensions": "7x5x1",
          "color": "Многоцветный",
          "rating": 4.5,
          "reviews_count": 80,
          "images": ["/media/img39.jpg", "/media/img40.jpg"],
          "seller_id": 120,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "abcd12345678"
      },
      {
          "id": 21,
          "name": "Трюфельное масло",
          "description": "Масло с ароматом трюфелей",
          "price": 19.99,
          "discount_price": 15.99,
          "stock": 25,
          "category": "Продукты",
          "created_at": "2024-03-05",
          "updated_at": "2024-03-15",
          "brand": "Restaurant",
          "weight": 0.5,
          "dimensions": "5x5x10",
          "color": "Прозрачный",
          "rating": 4.8,
          "reviews_count": 29,
          "images": ["/media/img41.jpg", "/media/img42.jpg"],
          "seller_id": 121,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "efgh12345678"
      },
      {
          "id": 22,
          "name": "Мини-печка",
          "description": "Персональная печь для выпечки",
          "price": 199.99,
          "discount_price": 179.99,
          "stock": 10,
          "category": "Кухня",
          "created_at": "2024-03-10",
          "updated_at": "2024-03-20",
          "brand": "Ariete",
          "weight": 3.0,
          "dimensions": "12x12x15",
          "color": "Белый",
          "rating": 4.7,
          "reviews_count": 60,
          "images": ["/media/img43.jpg", "/media/img44.jpg"],
          "seller_id": 122,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "ijkl12345678"
      },
      {
          "id": 23,
          "name": "Ультразвуковой увлажнитель",
          "description": "Увлажнитель воздуха с таймером",
          "price": 39.99,
          "discount_price": 29.99,
          "stock": 15,
          "category": "Кухня",
          "created_at": "2024-03-15",
          "updated_at": "2024-03-25",
          "brand": "Xiaomi",
          "weight": 1.0,
          "dimensions": "8x8x10",
          "color": "Белый",
          "rating": 4.5,
          "reviews_count": 50,
          "images": ["/media/img45.jpg", "/media/img46.jpg"],
          "seller_id": 123,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "mnop12345678"
      },
      {
          "id": 24,
          "name": "Кратерный шоколад",
          "description": "Шоколад с орехами и изюмом",
          "price": 5.99,
          "discount_price": 4.99,
          "stock": 100,
          "category": "Сладости",
          "created_at": "2024-03-20",
          "updated_at": "2024-03-30",
          "brand": "Chocola",
          "weight": 0.2,
          "dimensions": "5x5x1",
          "color": "Коричневый",
          "rating": 4.3,
          "reviews_count": 87,
          "images": ["/media/img47.jpg", "/media/img48.jpg"],
          "seller_id": 124,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "qrst12345678"
      },
      {
          "id": 25,
          "name": "Кресло для отдыха",
          "description": "Комфортное кресло с мягкой обивкой",
          "price": 189.99,
          "discount_price": 159.99,
          "stock": 8,
          "category": "Мебель",
          "created_at": "2024-03-25",
          "updated_at": "2024-04-04",
          "brand": "IKEA",
          "weight": 15.0,
          "dimensions": "80x80x100",
          "color": "Серый",
          "rating": 4.6,
          "reviews_count": 65,
          "images": ["/media/img49.jpg", "/media/img50.jpg"],
          "seller_id": 125,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "uvwxyz12345678"
      },
      {
          "id": 26,
          "name": "Детская игрушка",
          "description": "Яркая и безопасная игрушка для детей",
          "price": 19.99,
          "discount_price": 14.99,
          "stock": 50,
          "category": "Детские товары",
          "created_at": "2024-04-01",
          "updated_at": "2024-04-10",
          "brand": "Toys",
          "weight": 0.3,
          "dimensions": "10x10x10",
          "color": "Разноцветный",
          "rating": 4.8,
          "reviews_count": 90,
          "images": ["/media/img51.jpg", "/media/img52.jpg"],
          "seller_id": 126,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "123456yzabcd"
      },
      {
          "id": 27,
          "name": "Ароматизатор воздуха",
          "description": "Ароматизатор с эффектом ароматерапии",
          "price": 29.99,
          "discount_price": 24.99,
          "stock": 20,
          "category": "Аксессуары",
          "created_at": "2024-04-05",
          "updated_at": "2024-04-15",
          "brand": "Aromas",
          "weight": 0.5,
          "dimensions": "5x5x10",
          "color": "Белый",
          "rating": 4.5,
          "reviews_count": 25,
          "images": ["/media/img53.jpg", "/media/img54.jpg"],
          "seller_id": 127,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "abcd45312345"
      },
      {
          "id": 28,
          "name": "Суши-материалы",
          "description": "Комплект для приготовления суши в домашних условиях",
          "price": 49.99,
          "discount_price": 39.99,
          "stock": 35,
          "category": "Продукты",
          "created_at": "2024-04-10",
          "updated_at": "2024-04-20",
          "brand": "SushiTime",
          "weight": 1.0,
          "dimensions": "20x10x5",
          "color": "Многоцветный",
          "rating": 4.9,
          "reviews_count": 60,
          "images": ["/media/img55.jpg", "/media/img56.jpg"],
          "seller_id": 128,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "1234abcd5678"
      },
      {
          "id": 29,
          "name": "Аккумуляторная дрель",
          "description": "Мощная дрель для дома и строительства",
          "price": 129.99,
          "discount_price": 119.99,
          "stock": 7,
          "category": "Инструменты",
          "created_at": "2024-04-15",
          "updated_at": "2024-04-25",
          "brand": "Bosch",
          "weight": 1.8,
          "dimensions": "10x10x15",
          "color": "Черный",
          "rating": 4.7,
          "reviews_count": 30,
          "images": ["/media/img57.jpg", "/media/img58.jpg"],
          "seller_id": 129,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "9087xyz12345"
      },
      {
          "id": 30,
          "name": "Термосумка",
          "description": "Сумка для переноски еды и напитков",
          "price": 24.99,
          "discount_price": 19.99,
          "stock": 15,
          "category": "Аксессуары",
          "created_at": "2024-04-20",
          "updated_at": "2024-04-30",
          "brand": "EcoBag",
          "weight": 0.5,
          "dimensions": "30x20x10",
          "color": "Синий",
          "rating": 4.4,
          "reviews_count": 80,
          "images": ["/media/img59.jpg", "/media/img60.jpg"],
          "seller_id": 130,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "asf45312zxc"
      },
      {
          "id": 31,
          "name": "Картридж для принтера",
          "description": "Картридж для черно-белой печати",
          "price": 39.99,
          "discount_price": 34.99,
          "stock": 50,
          "category": "Канцтовары",
          "created_at": "2024-04-25",
          "updated_at": "2024-05-05",
          "brand": "Canon",
          "weight": 0.1,
          "dimensions": "10x3x5",
          "color": "Черный",
          "rating": 4.6,
          "reviews_count": 90,
          "images": ["/media/img61.jpg", "/media/img62.jpg"],
          "seller_id": 131,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "xx3456yyz12"
      },
      {
          "id": 32,
          "name": "Шведская стенка для детей",
          "description": "Шведская стенка для тренировок и игр",
          "price": 199.99,
          "discount_price": 179.99,
          "stock": 5,
          "category": "Игрушки",
          "created_at": "2024-05-01",
          "updated_at": "2024-05-10",
          "brand": "Play",
          "weight": 15.0,
          "dimensions": "70x20x120",
          "color": "Деревянный",
          "rating": 4.8,
          "reviews_count": 45,
          "images": ["/media/img63.jpg", "/media/img64.jpg"],
          "seller_id": 132,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "7543219876"
      },
      {
          "id": 33,
          "name": "Пылесос для сухой и влажной уборки",
          "description": "Многофункциональный пылесос",
          "price": 299.99,
          "discount_price": 279.99,
          "stock": 8,
          "category": "Уборка",
          "created_at": "2024-05-05",
          "updated_at": "2024-05-15",
          "brand": "Philips",
          "weight": 2.5,
          "dimensions": "30x30x30",
          "color": "Синий",
          "rating": 4.7,
          "reviews_count": 100,
          "images": ["/media/img65.jpg", "/media/img66.jpg"],
          "seller_id": 133,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "abcdef98765"
      },
      {
          "id": 34,
          "name": "Лампа LED",
          "description": "Энергоэффективная LED лампа",
          "price": 15.99,
          "discount_price": 12.99,
          "stock": 200,
          "category": "Освещение",
          "created_at": "2024-05-10",
          "updated_at": "2024-05-20",
          "brand": "Philips",
          "weight": 0.1,
          "dimensions": "5x5x10",
          "color": "Белый",
          "rating": 4.5,
          "reviews_count": 120,
          "images": ["/media/img67.jpg", "/media/img68.jpg"],
          "seller_id": 134,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "abc456def"
      },
      {
          "id": 35,
          "name": "Кошелек",
          "description": "Стильный кожаный кошелек",
          "price": 29.99,
          "discount_price": 24.99,
          "stock": 45,
          "category": "Аксессуары",
          "created_at": "2024-05-15",
          "updated_at": "2024-05-25",
          "brand": "Gucci",
          "weight": 0.2,
          "dimensions": "10x2x8",
          "color": "Черный",
          "rating": 4.6,
          "reviews_count": 34,
          "images": ["/media/img69.jpg", "/media/img70.jpg"],
          "seller_id": 135,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "gh1234ijk"
      },
      {
          "id": 36,
          "name": "Микроволновая печь",
          "description": "Микроволновая печь с автоматическими программами",
          "price": 149.99,
          "discount_price": 139.99,
          "stock": 10,
          "category": "Кухня",
          "created_at": "2024-05-20",
          "updated_at": "2024-05-30",
          "brand": "LG",
          "weight": 10.0,
          "dimensions": "30x20x20",
          "color": "Серебристый",
          "rating": 4.8,
          "reviews_count": 77,
          "images": ["/media/img71.jpg", "/media/img72.jpg"],
          "seller_id": 136,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "xyz123mnop"
      },
      {
          "id": 37,
          "name": "Веник и совок",
          "description": "Комплект для уборки",
          "price": 15.99,
          "discount_price": 12.99,
          "stock": 50,
          "category": "Уборка",
          "created_at": "2024-05-25",
          "updated_at": "2024-06-04",
          "brand": "EcoClean",
          "weight": 0.5,
          "dimensions": "100x25x10",
          "color": "Разноцветный",
          "rating": 4.3,
          "reviews_count": 45,
          "images": ["/media/img73.jpg", "/media/img74.jpg"],
          "seller_id": 137,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "abcd987654321"
      },
      {
          "id": 38,
          "name": "Спортивный инвентарь",
          "description": "Набор для фитнеса",
          "price": 99.99,
          "discount_price": 89.99,
          "stock": 20,
          "category": "Спорт",
          "created_at": "2024-06-01",
          "updated_at": "2024-06-11",
          "brand": "FitGear",
          "weight": 2.0,
          "dimensions": "30x30x15",
          "color": "Синий",
          "rating": 4.6,
          "reviews_count": 56,
          "images": ["/media/img75.jpg", "/media/img76.jpg"],
          "seller_id": 138,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "abcd112233"
      },
      {
          "id": 39,
          "name": "Гарнитура для наушников",
          "description": "Удобные наушники с микрофоном",
          "price": 49.99,
          "discount_price": 39.99,
          "stock": 30,
          "category": "Аудио",
          "created_at": "2024-06-05",
          "updated_at": "2024-06-15",
          "brand": "Razer",
          "weight": 0.7,
          "dimensions": "2x2x2",
          "color": "Черный",
          "rating": 4.4,
          "reviews_count": 22,
          "images": ["/media/img77.jpg", "/media/img78.jpg"],
          "seller_id": 139,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "efgh998877"
      },
      {
          "id": 40,
          "name": "Электрощетка Oral-B",
          "description": "Электрическая зубная щетка с таймером",
          "price": 89.99,
          "discount_price": 79.99,
          "stock": 40,
          "category": "Гигиена",
          "created_at": "2024-06-10",
          "updated_at": "2024-06-20",
          "brand": "Oral-B",
          "weight": 0.5,
          "dimensions": "8x2x10",
          "color": "Белый",
          "rating": 4.5,
          "reviews_count": 60,
          "images": ["/media/img79.jpg", "/media/img80.jpg"],
          "seller_id": 140,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "mnop87654321"
      },
      {
          "id": 41,
          "name": "Сетевой фильтр",
          "description": "Сетевой фильтр с защитой от перепадов напряжения",
          "price": 29.99,
          "discount_price": 24.99,
          "stock": 90,
          "category": "Электроника",
          "created_at": "2024-06-15",
          "updated_at": "2024-06-25",
          "brand": "TP-Link",
          "weight": 0.5,
          "dimensions": "10x5x5",
          "color": "Серебристый",
          "rating": 4.3,
          "reviews_count": 20,
          "images": ["/media/img81.jpg", "/media/img82.jpg"],
          "seller_id": 141,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "qrst87655321"
      },
      {
          "id": 42,
          "name": "Пекторальные эллементы",
          "description": "Тренажер для грудных мышц",
          "price": 149.99,
          "discount_price": 139.99,
          "stock": 15,
          "category": "Спорт",
          "created_at": "2024-06-20",
          "updated_at": "2024-06-30",
          "brand": "SportLine",
          "weight": 5.0,
          "dimensions": "80x60x60",
          "color": "Серый",
          "rating": 4.6,
          "reviews_count": 30,
          "images": ["/media/img83.jpg", "/media/img84.jpg"],
          "seller_id": 142,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "uio87654321"
      },
      {
          "id": 43,
          "name": "Скейтборд",
          "description": "Классический скейтборд для катания",
          "price": 89.99,
          "discount_price": 69.99,
          "stock": 12,
          "category": "Спорт",
          "created_at": "2024-06-25",
          "updated_at": "2024-07-05",
          "brand": "Element",
          "weight": 2.0,
          "dimensions": "80x20x5",
          "color": "Разноцветный",
          "rating": 4.2,
          "reviews_count": 25,
          "images": ["/media/img85.jpg", "/media/img86.jpg"],
          "seller_id": 143,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "abc123xyz"
      },
      {
          "id": 44,
          "name": "Спортивная бутылка",
          "description": "Бутылка для воды из нержавеющей стали",
          "price": 19.99,
          "discount_price": 15.99,
          "stock": 60,
          "category": "Аксессуары",
          "created_at": "2024-07-01",
          "updated_at": "2024-07-10",
          "brand": "Hydro Flask",
          "weight": 0.25,
          "dimensions": "7x7x23",
          "color": "Черный",
          "rating": 4.5,
          "reviews_count": 50,
          "images": ["/media/img87.jpg", "/media/img88.jpg"],
          "seller_id": 144,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "xyz987654321"
      },
      {
          "id": 45,
          "name": "Беспроводная зарядка",
          "description": "Зарядка для совместимых мобильных устройств",
          "price": 29.99,
          "discount_price": 24.99,
          "stock": 35,
          "category": "Аксессуары",
          "created_at": "2024-07-05",
          "updated_at": "2024-07-15",
          "brand": "Anker",
          "weight": 0.15,
          "dimensions": "10x10x1",
          "color": "Черный",
          "rating": 4.4,
          "reviews_count": 40,
          "images": ["/media/img89.jpg", "/media/img90.jpg"],
          "seller_id": 145,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "12345zzxx"
      },
      {
          "id": 46,
          "name": "Кроссовки для бега",
          "description": "Легкие кроссовки для повседневной носки",
          "price": 69.99,
          "discount_price": 59.99,
          "stock": 25,
          "category": "Одежда",
          "created_at": "2024-07-10",
          "updated_at": "2024-07-20",
          "brand": "Nike",
          "weight": 0.8,
          "dimensions": "30x20x10",
          "color": "Черный",
          "rating": 4.5,
          "reviews_count": 88,
          "images": ["/media/img91.jpg", "/media/img92.jpg"],
          "seller_id": 146,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "65432yytree"
      },
      {
          "id": 47,
          "name": "Спортивный рюкзак",
          "description": "Удобный рюкзак для спорта и поездок",
          "price": 49.99,
          "discount_price": 39.99,
          "stock": 40,
          "category": "Аксессуары",
          "created_at": "2024-07-15",
          "updated_at": "2024-07-25",
          "brand": "Adidas",
          "weight": 0.6,
          "dimensions": "30x15x45",
          "color": "Синий",
          "rating": 4.6,
          "reviews_count": 60,
          "images": ["/media/img93.jpg", "/media/img94.jpg"],
          "seller_id": 147,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "11111abba"
      },
      {
          "id": 48,
          "name": "Курсы по программированию",
          "description": "Онлайн-курсы по программированию",
          "price": 199.99,
          "discount_price": 179.99,
          "stock": 0, // Нет в наличии
          "category": "Услуги",
          "created_at": "2024-07-20",
          "updated_at": "2024-07-30",
          "brand": "SkillShare",
          "weight": 0.0,
          "dimensions": "0",
          "color": "Разноцветный",
          "rating": 4.8,
          "reviews_count": 150,
          "images": ["/media/img95.jpg", "/media/img96.jpg"],
          "seller_id": 148,
          "warranty_period": 0,
          "return_policy": "Нет возврата",
          "barcode": "99999caddy"
      },
      {
          "id": 49,
          "name": "Белый шоколад",
          "description": "Белый шоколад с добавлением орехов",
          "price": 15.99,
          "discount_price": 12.99,
          "stock": 50,
          "category": "Сладости",
          "created_at": "2024-08-01",
          "updated_at": "2024-08-10",
          "brand": "Milka",
          "weight": 0.1,
          "dimensions": "5x5x1",
          "color": "Белый",
          "rating": 4.7,
          "reviews_count": 45,
          "images": ["/media/img97.jpg", "/media/img98.jpg"],
          "seller_id": 149,
          "warranty_period": 0,
          "return_policy": "Нет возврата",
          "barcode": "22222yoga"
      },
      {
          "id": 50,
          "name": "Электрическая зубная щетка Oral-B",
          "description": "Электрическая зубная щетка с функцией автоматической очистки",
          "price": 89.99,
          "discount_price": 79.99,
          "stock": 80,
          "category": "Гигиена",
          "created_at": "2024-08-05",
          "updated_at": "2024-08-15",
          "brand": "Oral-B",
          "weight": 0.2,
          "dimensions": "10x3x10",
          "color": "Серый",
          "rating": 4.9,
          "reviews_count": 100,
          "images": ["/media/img99.jpg", "/media/img100.jpg"],
          "seller_id": 150,
          "warranty_period": 12,
          "return_policy": "14 дней на возврат",
          "barcode": "33333braid"
      }
  ]
};
